<?php
//get uuke_pads table row.
function get_uuke_pads_row_by_device_id($device_id){
	$query = db_select('uuke_pads', 'p');
	$result = $query
		->fields('p')
		->condition('p.device_id',$device_id)
		->execute()
    ->fetchAssoc();
  return $result;
}
/**
 * Implements hook_init().
 */
///?q=home&pid=12345678
function uuke_pad_init() {
	if (isset($_REQUEST['pid'])) {
		$apps = uuke_pad_app_get_list(TRUE);
		$my_settings = array(
		  'apps' => $apps,
		 );
		drupal_add_js(array('uuke_pad' => $my_settings), 'setting');

		$device_id = $_REQUEST['pid'];
		$pad = get_uuke_pads_row_by_device_id($device_id);
    if(!$pad){
    	dpm('首次访问，看看向导吧!');
    		db_insert('uuke_pads', array())
    			->fields(array(
						  'device_id' => $device_id,
						  'register_time' => REQUEST_TIME,
						  'access' => REQUEST_TIME,
						  'totalcount' =>1,
						))
					->execute();
    	}else {
    		global $base_path;
				if(current_path() == 'home') {
    		dpm("这是您的第".($pad['totalcount']+1)."次访问");
					$query = db_update('uuke_pads')
						->fields(array(
							  'access' => REQUEST_TIME,
						  	'totalcount' => ++$pad['totalcount'],
							))
						->condition('device_id',$device_id)
						->execute();
				}
    	}

	}
}

/**
 * Implements hook_node_view().
 */
function uuke_pad_node_view($node, $view_mode, $langcode) {
	if($node->type == 'app' && $view_mode=='full') {
		// $my_variables = array('app_id' => $node->nid, ); // and so on
		// drupal_add_js(array('uuke_pad' => $my_variables), 'setting'); // 
		drupal_add_js(drupal_get_path('module','uuke_pad').'/app_install.js', 'file');
		$pad = get_uuke_pads_row_by_device_id($device_id='123456');
		
		$app_node = node_load(1);
		$app_vid = uuke_pad_is_installed($pad, $app_node);
		dvm($app_vid);
	}
}


/**
 * Implements hook_menu().
 */
function uuke_pad_menu() {
	$items = array();
	//http://market/?q=app/manage/install&package_name=translate.google.com&pid=123456  &dev=1
	$items['app/manage/%'] = array(
		'title' => '',
		'page callback' => 'uuke_pad_app_manage',
    'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	$items['app/get_list'] = array(
		'title' => '',
		'page callback' => 'uuke_pad_app_get_list',
    'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);
	return $items;
}
/**
 * @return
 * op==install 
 * app_install 
 * 1已安装guo,ceng卸载 版本号是:xianzaigengxin
 * 2无需安装，记录已存在!
 * 3还未安装，现在安装
 */
function uuke_pad_app_manage($op = 'install') {
	$return = array();
	$return['app_manage_op'] = $op;
	$package_name =  $_REQUEST['package_name'];
	$device_id = $_REQUEST['pid'];
	$app_id = get_app_id_by_package_name($package_name);
	$app_node = node_load($app_id);
	$return['app_latest_vid'] = $app_node->vid;
	$pad = get_uuke_pads_row_by_device_id($device_id);
	$app_history_record = uuke_pad_history_record($pad, $app_node);
	if($op == 'install') {
	//check & update db
		if(isset($app_history_record['vid'])) {

			$return['local_app_vid'] = $app_history_record['vid'];
			$return['app_install'] = 1;
			if($app_history_record['status'] == 0) {
					$query = db_update('uuke_pad_history')
						->fields(array(
							  'status' => 1,
							  'vid' => $app_node->vid,
							))
						->condition('pid',$pad['pid'])
						->condition('nid',$app_node->nid)
						->execute();
			dpm($return,'已安装guo,ceng卸载 版本号是:xianzaigengxin');
			}else{
				$return['app_install'] = 2;
				dpm('无需安装，记录已存在!');
			}
		}else {
			//安装
			dpm('还未安装，现在安装!');
			$return['app_install'] = 3;
		  $record = array (
		    "pid" => $pad['pid'],
		    "vid" => $app_node->vid,
		    "nid" => $app_node->nid,
		    // "status" => 1,
	    );
	    drupal_write_record('uuke_pad_history', $record);
		}
	}elseif ($op == 'uninstall') {
		//check & delete
		$query = db_update('uuke_pad_history')
		->fields(array(
			  'status' => 0,
			))
		->condition('pid',$pad['pid'])
		->condition('nid',$app_node->nid)
		->execute();
		$return['op_status'] = TRUE;
	}elseif ($op == 'update') {
		if($app_history_record['vid']!=$app_node->vid)
		$query = db_update('uuke_pad_history')
			->fields(array(
		    	"vid" => $app_node->vid,
				))
			->condition('pid',$pad['pid'])
			->condition('nid',$app_node->nid)
			->execute();
		$return['op_status'] = TRUE;
	}else {
		watchdog('uuke_pad', 'uuke_pad_app_manage give wrong param', array(), WATCHDOG_NOTICE, 'warning');
	}
	dpm($return);
	if(isset($_REQUEST['dev'])) return '';
	return  drupal_json_output($return);
}

// @return  app node id / FALSE
// array(
//   'entity_id' => '1',
// )
function get_app_id_by_package_name($package_name) {
  $query = db_select('field_data_field_app_package_name', 'f');
  $query->join('node','n','n.nid = f.entity_id');
  $result = $query
    ->fields('f', array('entity_id'))//nid
    ->condition('f.field_app_package_name_value',$package_name)
    // ->condition('n.type ','app')
    ->condition('f.bundle ','app')
    ->condition('n.status',1)
    ->execute()
    ->fetchAssoc();
  //should be only one node.
  return $result['entity_id'];
}

function uuke_pad_history_record($pad,$app_node) {
	$query = db_select('uuke_pad_history', 'h');
  $result = $query
    ->fields('h')
    ->condition('h.nid ',$app_node->nid)
    ->condition('h.pid ',$pad['pid'])
    // ->condition('h.status ',1)
    ->execute()
    ->fetchAssoc();
  return $result;
}
function uuke_pad_is_installed($pad,$app_node) {
	$query = db_select('uuke_pad_history', 'h');
  $result = $query
    ->fields('h', array('vid','status'))
    ->condition('h.nid ',$app_node->nid)
    ->condition('h.pid ',$pad['pid'])
    ->condition('h.status ',1)
    ->execute()
    ->fetchAssoc();
  return $result['vid'];//app_vid
}
//return package_name array.
function uuke_pad_app_get_list($json_output=FALSE) {
	$device_id = $_REQUEST['pid'];
	$pad = get_uuke_pads_row_by_device_id($device_id);
	$query = db_select('uuke_pad_history', 'h');
  $result = $query
    ->fields('h',array('nid'))
    ->condition('h.pid ',$pad['pid'])
    ->condition('h.status ',1)
    ->execute()
    ->fetchCol();
  foreach ($result as $key => $nid) {
  	$return[] = node_load($nid)->field_app_package_name[LANGUAGE_NONE][0]['value'];
  	# code...
  }
  if(isset($_REQUEST['dev'])) return '';
  if($json_output) return $return;
	return  drupal_json_output($return);
}